name: ci
title: test
run-on: heroku
kind: 🪁
package: dns.python.javascript
bundle: rake.i
on:
  pull_request: paradice/bitore.sig
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['2.1', '2.2', '3.0', '3.1', '5.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clear toolcache
        shell: pwsh
        run: __tests__/clear-toolcache.ps1 ${{ runner.os }}
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: ./
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
Name: Job
Job: Construction
Construction: gemfile
gemfile: {{{{${[(secrets)]}.{[VOLUME].00].denom}}_{ITEM_ID}}}"''
:BUILD:: integrity::BEGIN:
